pipeline {
  agent any

  environment {
    AWS_REGION = 'us-east-2'
    // Set these in Jenkins job config:
    // FRONTEND_BUCKET = '...'
    // CLOUDFRONT_DISTRIBUTION_ID = '...'
  }

  stages {
    stage('Checkout') { steps { checkout scm } }

    stage('Install') { steps { sh 'npm ci' } }

    stage('Build') { steps { sh 'npm run build' } }

    stage('Deploy to S3 + Invalidate CloudFront') {
      steps {
        sh '''
          aws s3 sync build/ "s3://$FRONTEND_BUCKET" --delete --region "$AWS_REGION"
          aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" --paths "/*"
        '''
      }
    }
  }
}